name: Deploy Bicep to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep Modules
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: taha
          template: ./bicep/main.bicep
          parameters: location=eastus resourceGroupName=taha
          deploymentName: deploy-modular-bicep

      - name: Verify Deployment
        run: |
          az group show --name taha
          az network vnet list --resource-group taha
          az vm list --resource-group taha
          az storage account list --resource-group taha

      - name: Logout from Azure
        run: az logout
